version: "3.6"
services:
  postgres:
    ports:
      - "5432:5432"
  admin:
    command: >
      sh -c "npm i && npm run serve"
  graphql-engine:
    environment:
      HASURA_GRAPHQL_DEV_MODE: "true"
